<a href="https://colab.research.google.com/github/swetha-crack-it/Datascience-/blob/main/Data_science_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
path="/content/IMDb Movies India.csv"
df=pd.read_csv(path,encoding='latin')
df.head()

Name    Year Duration            Genre  \
0                                         NaN      NaN            Drama   
1  #Gadhvi (He thought he was Gandhi)  (2019)  109 min            Drama   
2                         #Homecoming  (2021)   90 min   Drama, Musical   
3                             #Yaaram  (2019)  110 min  Comedy, Romance   
4                   ...And Once Again  (2010)  105 min            Drama   

   Rating Votes            Director       Actor 1             Actor 2  \
0     NaN   NaN       J.S. Randhawa      Manmauji              Birbal   
1     7.0     8       Gaurav Bakshi  Rasika Dugal      Vivek Ghamande   
2     NaN   NaN  Soumyajit Majumdar  Sayani Gupta   Plabita Borthakur   
3     4.4    35          Ovais Khan       Prateik          Ishita Raj   
4     NaN   NaN        Amol Palekar  Rajat Kapoor  Rituparna Sengupta   

           Actor 3  
0  Rajendra Bhatia  
1    Arvind Jangid  
2       Roy Angana  
3  Siddhant Kapoor  
4      Antara Mali

In [ ]:
print(df.isnull().sum())


Name           0
Year         528
Duration    8269
Genre       1877
Rating      7590
Votes       7589
Director     525
Actor 1     1617
Actor 2     2384
Actor 3     3144
dtype: int64


In [ ]:
df.dropna(inplace=True)

In [ ]:

df.fillna(df['Year'].mode()[0], inplace=True)  # For categorical columns

In [ ]:

df.fillna(df['Duration'].mode()[0], inplace=True)  # For categorical columns

In [ ]:

df.fillna(df['Genre'].mode()[0], inplace=True)  # For categorical columns

In [ ]:

df.fillna(df['Rating'].mode()[0], inplace=True)  # For categorical columns

In [ ]:


df.fillna(df['Votes'].mode()[0], inplace=True)  # For categorical columns'].mode()[0], inplace=True)  # For categorical columns

In [ ]:

df.fillna(df['Director'].mode()[0], inplace=True)  # For categorical columns

In [ ]:

df.fillna(df['Actor 1'].mode()[0], inplace=True)  # For categorical columns

In [ ]:

df.fillna(df['Actor 2'].mode()[0], inplace=True)  # For categorical columns

In [ ]:

df.fillna(df['Actor 3'].mode()[0], inplace=True)

In [ ]:
print(df.isnull().sum())

Name        0
Year        0
Duration    0
Genre       0
Rating      0
Votes       0
Director    0
Actor 1     0
Actor 2     0
Actor 3     0
dtype: int64


In [1]:
import pandas as pd

# Load from the correct path (uploaded location)
df = pd.read_csv("/content/cleaned movie dataset.csv")


In [2]:
# Clean Year
df['Year'] = df['Year'].str.extract(r'(\d{4})').astype(int)

# Clean Duration
df['Duration'] = df['Duration'].str.extract(r'(\d+)').astype(int)

# Clean Votes
df['Votes'] = df['Votes'].str.replace(',', '').astype(int)

# Standardize categorical text
for col in ['Genre', 'Director', 'Actor 1', 'Actor 2', 'Actor 3']:
    df[col] = df[col].str.strip().str.lower()


In [3]:
df.to_csv("C:\\Users\\Kuljirajan\\Downloads\\Data\\cleaned movie dataset.csv", index=False)


In [4]:
print(df['Year'].unique()[:10])  # View first 10 unique years
print(df['Year'].dtype)          # Should be int or int64


[2019 1997 2005 2012 2014 2004 2016 1991 2018 2010]
int64


In [5]:
print(df['Duration'].unique()[:10])
print(df['Duration'].dtype)


[109 110 147 142  82 116  96 120 161 166]
int64


In [ ]:
print(df['Votes'].unique()[:10])
print(df['Votes'].dtype)


[   8   35  827 1086  326   11   17   59  983  512]
int64


In [6]:
for col in ['Genre', 'Director', 'Actor 1', 'Actor 2', 'Actor 3']:
    print(f"{col} examples: {df[col].unique()[:5]}")


Genre examples: ['drama' 'comedy, romance' 'comedy, drama, musical' 'drama, romance, war'
 'horror, mystery, thriller']
Director examples: ['gaurav bakshi' 'ovais khan' 'rahul rawail' 'shoojit sircar'
 'allyson patel']
Actor 1 examples: ['rasika dugal' 'prateik' 'bobby deol' 'jimmy sheirgill' 'yash dave']
Actor 2 examples: ['vivek ghamande' 'ishita raj' 'aishwarya rai bachchan' 'minissha lamba'
 'muntazir ahmad']
Actor 3 examples: ['arvind jangid' 'siddhant kapoor' 'shammi kapoor' 'yashpal sharma'
 'kiran bhatia']


In [7]:
# Core ML tools
import pandas as pd
import numpy as np

# Models
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR

# XGBoost (only if installed)
try:
    from xgboost import XGBRegressor
except ImportError:
    print("XGBoost not installed. You can install it using: pip install xgboost")


In [8]:
from sklearn.model_selection import train_test_split

# Separate features and target
X = df.drop('Rating', axis=1)
y = df['Rating']

# Only keep numeric features (for now)
X = X.select_dtypes(include=[np.number])

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


In [12]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)


In [13]:
import numpy as np
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

print("R² Score:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))
print("RMSE:", rmse)


R² Score: 0.07798737059748773
MAE: 1.060606221312931
RMSE: 1.3066487776555733


In [14]:
coefficients = model.coef_
features = X.columns

for feat, coef in zip(features, coefficients):
    print(f"{feat}: {coef:.4f}")


Year: -0.0187
Duration: -0.0061
Votes: 0.0000
